# /etc/netplan/00-installer-config.yaml
network:
  ethernets:
    ens18:
      dhcp4: no
      addresses: [192.168.1.10/24] # master: .10, worker1: .11, worker2: .12
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
  version: 2
